# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions and https://github.com/actions/setup-node

name: Deploy CI

on:
  push:
    branches: [ main, joaopaulo ]
  pull_request:
    branches: [ main, joaopaulo ]

env:
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
  APP_NAME: ${{ 'codelitt-calendar' }}

jobs:
  deploy:
    name: Deploy to Heroku
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    # Build Docker image
    - name: Docker build -f Dockerfile.prod
      run: docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com

    # Push the Docker image to Heroku Container Registry
    - name: Publish
      run: |
        heroku container:push web -a $APP_NAME
        heroku container:release web -a $APP_NAME
